edit:
    - added
    - and and
    - and it
    - at it
    - that it
    - had it
    - ended
    - handed
    - and eight
apply: ['applied']
top: ['dopp', 'dup', 'dog']
kill: ['gill', 'bill', 'skill', 'killed', 'deal', 'goal']
alpha: ['have fun', "i'll fly"]
escape: ['a scape', 'as cape', 's. cape']
'yes':
    - years
    - us
    - yep
    - affirmative
    - definitely
    - for sure
screen: ['screening', 'green']
press escape: ['precious cape', 'presence cape']
mark: ['market']
select: ['so like', 'so liked', 'so let', 'she liked', 'she left', 'so look', "so that's", "so let's"]
delete: ['elite', 'delayed', 'lead', 'delays']
maximize: ['maximise']
execute: ['acts of yes', 'executes']
refresh: ['refreshed']
focus: ['focused']
print: ['printer', 'prince']
finish: ['finnish', 'fashion']
attach: ['in touch', 'touch', 'at the edge', "at that age"]
window: ['when know', 'when you']
right: ['write']
go end: ['go and']
insert: ['in short', 'desert']
tab: ['tub']
left: ['lest', 'less']
gamma: ['emma', 'ghana']
copy: ['kabul', 'can be', 'kobe']
press: ['pressed']
stop: ['stopped', 'star', 'stuff']
bigger: ['baker']
page up: ['age up']
erase: ['race']
chicago: ['she got off', 'she got the', 'she got of', 'she congo']
calendar: ['go under']
press enter: ['presenter']
sacrifice: ['sacrificed']
'no': ['now', 'know', 'i know']
tagging: ['taking', 'dragging', 'digging', 'thanking', 'dying']
pick: ['big']
beta: ['data']
custom: ['cost them', 'because them']
workspace: ['workplace']
