edit:
    - added
    - and and
    - and it
    - at it
    - that it
    - had it
    - ended
    - handed
    - and eight
apply: ['applied']
top: ['dopp', 'dup', 'dog']
kill: ['gill', 'bill', 'skill', 'killed']
alpha: ['have fun', "i'll fly"]
escape: ['a scape', 'as cape', 's. cape']
'yes':
    - years
    - us
    - yep
    - affirmative
    - definitely
    - for sure
screen: ['screening', 'green']
press escape: ['precious cape', 'presence cape']
mark: ['market']
select: ['so like', 'so liked', 'so let', 'she liked']
maximize: ['maximise']
focus: ['focused']
attach: ['in touch', 'touch', 'at the edge', "at that age"]
window: ['when know', 'when you']
right: ['write']
tab: ['tub']
left: ['lest', 'less']
gamma: ['emma', 'ghana']
copy: ['kabul', 'can be', 'kobe']
press: ['pressed']
stop: ['stopped']
'no': ['now', 'know', 'i know']
tagging: ['taking', 'dragging', 'digging', 'thanking', 'dying']
pick: ['big']
beta: ['data']
custom: ['cost them', 'because them']
workspace: ['workplace']
